// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimeCityBean.proto
// Protobuf Java Version: 4.26.1

package com.kieslect.kdata.proto.dto;

public final class TimeCityBeanProto {
  private TimeCityBeanProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      TimeCityBeanProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimeCityBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TimeCityBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    java.util.List<com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean> 
        getTimeBeanList();
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean getTimeBean(int index);
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    int getTimeBeanCount();
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    java.util.List<? extends com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder> 
        getTimeBeanOrBuilderList();
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder getTimeBeanOrBuilder(
        int index);

    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>int64 updateTime = 3;</code>
     * @return The updateTime.
     */
    long getUpdateTime();
  }
  /**
   * Protobuf type {@code TimeCityBean}
   */
  public static final class TimeCityBean extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TimeCityBean)
      TimeCityBeanOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        TimeCityBean.class.getName());
    }
    // Use TimeCityBean.newBuilder() to construct.
    private TimeCityBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TimeCityBean() {
      timeBean_ = java.util.Collections.emptyList();
      version_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeCityBean_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeCityBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean.class, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean.Builder.class);
    }

    public static final int TIMEBEAN_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean> timeBean_;
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean> getTimeBeanList() {
      return timeBean_;
    }
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder> 
        getTimeBeanOrBuilderList() {
      return timeBean_;
    }
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    @java.lang.Override
    public int getTimeBeanCount() {
      return timeBean_.size();
    }
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    @java.lang.Override
    public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean getTimeBean(int index) {
      return timeBean_.get(index);
    }
    /**
     * <code>repeated .TimeBean timeBean = 1;</code>
     */
    @java.lang.Override
    public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder getTimeBeanOrBuilder(
        int index) {
      return timeBean_.get(index);
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATETIME_FIELD_NUMBER = 3;
    private long updateTime_ = 0L;
    /**
     * <code>int64 updateTime = 3;</code>
     * @return The updateTime.
     */
    @java.lang.Override
    public long getUpdateTime() {
      return updateTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < timeBean_.size(); i++) {
        output.writeMessage(1, timeBean_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, version_);
      }
      if (updateTime_ != 0L) {
        output.writeInt64(3, updateTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < timeBean_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, timeBean_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, version_);
      }
      if (updateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, updateTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean)) {
        return super.equals(obj);
      }
      com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean other = (com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean) obj;

      if (!getTimeBeanList()
          .equals(other.getTimeBeanList())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (getUpdateTime()
          != other.getUpdateTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTimeBeanCount() > 0) {
        hash = (37 * hash) + TIMEBEAN_FIELD_NUMBER;
        hash = (53 * hash) + getTimeBeanList().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TimeCityBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TimeCityBean)
        com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeCityBean_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeCityBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean.class, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean.Builder.class);
      }

      // Construct using com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (timeBeanBuilder_ == null) {
          timeBean_ = java.util.Collections.emptyList();
        } else {
          timeBean_ = null;
          timeBeanBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = "";
        updateTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeCityBean_descriptor;
      }

      @java.lang.Override
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean getDefaultInstanceForType() {
        return com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean.getDefaultInstance();
      }

      @java.lang.Override
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean build() {
        com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean buildPartial() {
        com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean result = new com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean result) {
        if (timeBeanBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            timeBean_ = java.util.Collections.unmodifiableList(timeBean_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.timeBean_ = timeBean_;
        } else {
          result.timeBean_ = timeBeanBuilder_.build();
        }
      }

      private void buildPartial0(com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.updateTime_ = updateTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean) {
          return mergeFrom((com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean other) {
        if (other == com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean.getDefaultInstance()) return this;
        if (timeBeanBuilder_ == null) {
          if (!other.timeBean_.isEmpty()) {
            if (timeBean_.isEmpty()) {
              timeBean_ = other.timeBean_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTimeBeanIsMutable();
              timeBean_.addAll(other.timeBean_);
            }
            onChanged();
          }
        } else {
          if (!other.timeBean_.isEmpty()) {
            if (timeBeanBuilder_.isEmpty()) {
              timeBeanBuilder_.dispose();
              timeBeanBuilder_ = null;
              timeBean_ = other.timeBean_;
              bitField0_ = (bitField0_ & ~0x00000001);
              timeBeanBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTimeBeanFieldBuilder() : null;
            } else {
              timeBeanBuilder_.addAllMessages(other.timeBean_);
            }
          }
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getUpdateTime() != 0L) {
          setUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean m =
                    input.readMessage(
                        com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.parser(),
                        extensionRegistry);
                if (timeBeanBuilder_ == null) {
                  ensureTimeBeanIsMutable();
                  timeBean_.add(m);
                } else {
                  timeBeanBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                version_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                updateTime_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean> timeBean_ =
        java.util.Collections.emptyList();
      private void ensureTimeBeanIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          timeBean_ = new java.util.ArrayList<com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean>(timeBean_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder> timeBeanBuilder_;

      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public java.util.List<com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean> getTimeBeanList() {
        if (timeBeanBuilder_ == null) {
          return java.util.Collections.unmodifiableList(timeBean_);
        } else {
          return timeBeanBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public int getTimeBeanCount() {
        if (timeBeanBuilder_ == null) {
          return timeBean_.size();
        } else {
          return timeBeanBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean getTimeBean(int index) {
        if (timeBeanBuilder_ == null) {
          return timeBean_.get(index);
        } else {
          return timeBeanBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder setTimeBean(
          int index, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean value) {
        if (timeBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeBeanIsMutable();
          timeBean_.set(index, value);
          onChanged();
        } else {
          timeBeanBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder setTimeBean(
          int index, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder builderForValue) {
        if (timeBeanBuilder_ == null) {
          ensureTimeBeanIsMutable();
          timeBean_.set(index, builderForValue.build());
          onChanged();
        } else {
          timeBeanBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder addTimeBean(com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean value) {
        if (timeBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeBeanIsMutable();
          timeBean_.add(value);
          onChanged();
        } else {
          timeBeanBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder addTimeBean(
          int index, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean value) {
        if (timeBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeBeanIsMutable();
          timeBean_.add(index, value);
          onChanged();
        } else {
          timeBeanBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder addTimeBean(
          com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder builderForValue) {
        if (timeBeanBuilder_ == null) {
          ensureTimeBeanIsMutable();
          timeBean_.add(builderForValue.build());
          onChanged();
        } else {
          timeBeanBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder addTimeBean(
          int index, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder builderForValue) {
        if (timeBeanBuilder_ == null) {
          ensureTimeBeanIsMutable();
          timeBean_.add(index, builderForValue.build());
          onChanged();
        } else {
          timeBeanBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder addAllTimeBean(
          java.lang.Iterable<? extends com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean> values) {
        if (timeBeanBuilder_ == null) {
          ensureTimeBeanIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, timeBean_);
          onChanged();
        } else {
          timeBeanBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder clearTimeBean() {
        if (timeBeanBuilder_ == null) {
          timeBean_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          timeBeanBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public Builder removeTimeBean(int index) {
        if (timeBeanBuilder_ == null) {
          ensureTimeBeanIsMutable();
          timeBean_.remove(index);
          onChanged();
        } else {
          timeBeanBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder getTimeBeanBuilder(
          int index) {
        return getTimeBeanFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder getTimeBeanOrBuilder(
          int index) {
        if (timeBeanBuilder_ == null) {
          return timeBean_.get(index);  } else {
          return timeBeanBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public java.util.List<? extends com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder> 
           getTimeBeanOrBuilderList() {
        if (timeBeanBuilder_ != null) {
          return timeBeanBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(timeBean_);
        }
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder addTimeBeanBuilder() {
        return getTimeBeanFieldBuilder().addBuilder(
            com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.getDefaultInstance());
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder addTimeBeanBuilder(
          int index) {
        return getTimeBeanFieldBuilder().addBuilder(
            index, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.getDefaultInstance());
      }
      /**
       * <code>repeated .TimeBean timeBean = 1;</code>
       */
      public java.util.List<com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder> 
           getTimeBeanBuilderList() {
        return getTimeBeanFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder> 
          getTimeBeanFieldBuilder() {
        if (timeBeanBuilder_ == null) {
          timeBeanBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder>(
                  timeBean_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          timeBean_ = null;
        }
        return timeBeanBuilder_;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 2;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        version_ = getDefaultInstance().getVersion();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long updateTime_ ;
      /**
       * <code>int64 updateTime = 3;</code>
       * @return The updateTime.
       */
      @java.lang.Override
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <code>int64 updateTime = 3;</code>
       * @param value The updateTime to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateTime(long value) {

        updateTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 updateTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        updateTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TimeCityBean)
    }

    // @@protoc_insertion_point(class_scope:TimeCityBean)
    private static final com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean();
    }

    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimeCityBean>
        PARSER = new com.google.protobuf.AbstractParser<TimeCityBean>() {
      @java.lang.Override
      public TimeCityBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TimeCityBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimeCityBean> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeCityBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TimeBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TimeBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 ido_id = 1;</code>
     * @return The idoId.
     */
    long getIdoId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string country = 3;</code>
     * @return The country.
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 3;</code>
     * @return The bytes for country.
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>string timeZoneName = 4;</code>
     * @return The timeZoneName.
     */
    java.lang.String getTimeZoneName();
    /**
     * <code>string timeZoneName = 4;</code>
     * @return The bytes for timeZoneName.
     */
    com.google.protobuf.ByteString
        getTimeZoneNameBytes();

    /**
     * <code>string abbreviation = 5;</code>
     * @return The abbreviation.
     */
    java.lang.String getAbbreviation();
    /**
     * <code>string abbreviation = 5;</code>
     * @return The bytes for abbreviation.
     */
    com.google.protobuf.ByteString
        getAbbreviationBytes();

    /**
     * <code>double latitude = 6;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 7;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code TimeBean}
   */
  public static final class TimeBean extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TimeBean)
      TimeBeanOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        TimeBean.class.getName());
    }
    // Use TimeBean.newBuilder() to construct.
    private TimeBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TimeBean() {
      name_ = "";
      country_ = "";
      timeZoneName_ = "";
      abbreviation_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeBean_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.class, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder.class);
    }

    public static final int IDO_ID_FIELD_NUMBER = 1;
    private long idoId_ = 0L;
    /**
     * <code>int64 ido_id = 1;</code>
     * @return The idoId.
     */
    @java.lang.Override
    public long getIdoId() {
      return idoId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object country_ = "";
    /**
     * <code>string country = 3;</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 3;</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMEZONENAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timeZoneName_ = "";
    /**
     * <code>string timeZoneName = 4;</code>
     * @return The timeZoneName.
     */
    @java.lang.Override
    public java.lang.String getTimeZoneName() {
      java.lang.Object ref = timeZoneName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeZoneName_ = s;
        return s;
      }
    }
    /**
     * <code>string timeZoneName = 4;</code>
     * @return The bytes for timeZoneName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeZoneNameBytes() {
      java.lang.Object ref = timeZoneName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeZoneName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ABBREVIATION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object abbreviation_ = "";
    /**
     * <code>string abbreviation = 5;</code>
     * @return The abbreviation.
     */
    @java.lang.Override
    public java.lang.String getAbbreviation() {
      java.lang.Object ref = abbreviation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        abbreviation_ = s;
        return s;
      }
    }
    /**
     * <code>string abbreviation = 5;</code>
     * @return The bytes for abbreviation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAbbreviationBytes() {
      java.lang.Object ref = abbreviation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        abbreviation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 6;
    private double latitude_ = 0D;
    /**
     * <code>double latitude = 6;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 7;
    private double longitude_ = 0D;
    /**
     * <code>double longitude = 7;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idoId_ != 0L) {
        output.writeInt64(1, idoId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(country_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, country_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timeZoneName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, timeZoneName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(abbreviation_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, abbreviation_);
      }
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        output.writeDouble(6, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        output.writeDouble(7, longitude_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idoId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, idoId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(country_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, country_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timeZoneName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, timeZoneName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(abbreviation_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, abbreviation_);
      }
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, longitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean)) {
        return super.equals(obj);
      }
      com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean other = (com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean) obj;

      if (getIdoId()
          != other.getIdoId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getCountry()
          .equals(other.getCountry())) return false;
      if (!getTimeZoneName()
          .equals(other.getTimeZoneName())) return false;
      if (!getAbbreviation()
          .equals(other.getAbbreviation())) return false;
      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDO_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdoId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + TIMEZONENAME_FIELD_NUMBER;
      hash = (53 * hash) + getTimeZoneName().hashCode();
      hash = (37 * hash) + ABBREVIATION_FIELD_NUMBER;
      hash = (53 * hash) + getAbbreviation().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TimeBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TimeBean)
        com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeBean_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.class, com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.Builder.class);
      }

      // Construct using com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        idoId_ = 0L;
        name_ = "";
        country_ = "";
        timeZoneName_ = "";
        abbreviation_ = "";
        latitude_ = 0D;
        longitude_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kieslect.kdata.proto.dto.TimeCityBeanProto.internal_static_TimeBean_descriptor;
      }

      @java.lang.Override
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean getDefaultInstanceForType() {
        return com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.getDefaultInstance();
      }

      @java.lang.Override
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean build() {
        com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean buildPartial() {
        com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean result = new com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.idoId_ = idoId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.country_ = country_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.timeZoneName_ = timeZoneName_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.abbreviation_ = abbreviation_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.latitude_ = latitude_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.longitude_ = longitude_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean) {
          return mergeFrom((com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean other) {
        if (other == com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean.getDefaultInstance()) return this;
        if (other.getIdoId() != 0L) {
          setIdoId(other.getIdoId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getTimeZoneName().isEmpty()) {
          timeZoneName_ = other.timeZoneName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getAbbreviation().isEmpty()) {
          abbreviation_ = other.abbreviation_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                idoId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                country_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                timeZoneName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                abbreviation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 49: {
                latitude_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              case 57: {
                longitude_ = input.readDouble();
                bitField0_ |= 0x00000040;
                break;
              } // case 57
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long idoId_ ;
      /**
       * <code>int64 ido_id = 1;</code>
       * @return The idoId.
       */
      @java.lang.Override
      public long getIdoId() {
        return idoId_;
      }
      /**
       * <code>int64 ido_id = 1;</code>
       * @param value The idoId to set.
       * @return This builder for chaining.
       */
      public Builder setIdoId(long value) {

        idoId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ido_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdoId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        idoId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 3;</code>
       * @return The country.
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 3;</code>
       * @return The bytes for country.
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 3;</code>
       * @param value The country to set.
       * @return This builder for chaining.
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        country_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountry() {
        country_ = getDefaultInstance().getCountry();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string country = 3;</code>
       * @param value The bytes for country to set.
       * @return This builder for chaining.
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        country_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object timeZoneName_ = "";
      /**
       * <code>string timeZoneName = 4;</code>
       * @return The timeZoneName.
       */
      public java.lang.String getTimeZoneName() {
        java.lang.Object ref = timeZoneName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeZoneName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timeZoneName = 4;</code>
       * @return The bytes for timeZoneName.
       */
      public com.google.protobuf.ByteString
          getTimeZoneNameBytes() {
        java.lang.Object ref = timeZoneName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeZoneName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timeZoneName = 4;</code>
       * @param value The timeZoneName to set.
       * @return This builder for chaining.
       */
      public Builder setTimeZoneName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timeZoneName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string timeZoneName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeZoneName() {
        timeZoneName_ = getDefaultInstance().getTimeZoneName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string timeZoneName = 4;</code>
       * @param value The bytes for timeZoneName to set.
       * @return This builder for chaining.
       */
      public Builder setTimeZoneNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        timeZoneName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object abbreviation_ = "";
      /**
       * <code>string abbreviation = 5;</code>
       * @return The abbreviation.
       */
      public java.lang.String getAbbreviation() {
        java.lang.Object ref = abbreviation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          abbreviation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string abbreviation = 5;</code>
       * @return The bytes for abbreviation.
       */
      public com.google.protobuf.ByteString
          getAbbreviationBytes() {
        java.lang.Object ref = abbreviation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          abbreviation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string abbreviation = 5;</code>
       * @param value The abbreviation to set.
       * @return This builder for chaining.
       */
      public Builder setAbbreviation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        abbreviation_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string abbreviation = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAbbreviation() {
        abbreviation_ = getDefaultInstance().getAbbreviation();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string abbreviation = 5;</code>
       * @param value The bytes for abbreviation to set.
       * @return This builder for chaining.
       */
      public Builder setAbbreviationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        abbreviation_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 6;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 6;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {

        latitude_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000020);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 7;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 7;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {

        longitude_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000040);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TimeBean)
    }

    // @@protoc_insertion_point(class_scope:TimeBean)
    private static final com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean();
    }

    public static com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimeBean>
        PARSER = new com.google.protobuf.AbstractParser<TimeBean>() {
      @java.lang.Override
      public TimeBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TimeBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimeBean> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kieslect.kdata.proto.dto.TimeCityBeanProto.TimeBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeCityBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TimeCityBean_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TimeBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TimeCityBean.proto\"P\n\014TimeCityBean\022\033\n\010" +
      "timeBean\030\001 \003(\0132\t.TimeBean\022\017\n\007version\030\002 \001" +
      "(\t\022\022\n\nupdateTime\030\003 \001(\003\"\212\001\n\010TimeBean\022\016\n\006i" +
      "do_id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\017\n\007country\030\003 \001" +
      "(\t\022\024\n\014timeZoneName\030\004 \001(\t\022\024\n\014abbreviation" +
      "\030\005 \001(\t\022\020\n\010latitude\030\006 \001(\001\022\021\n\tlongitude\030\007 " +
      "\001(\001B1\n\034com.kieslect.kdata.proto.dtoB\021Tim" +
      "eCityBeanProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TimeCityBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TimeCityBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TimeCityBean_descriptor,
        new java.lang.String[] { "TimeBean", "Version", "UpdateTime", });
    internal_static_TimeBean_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TimeBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TimeBean_descriptor,
        new java.lang.String[] { "IdoId", "Name", "Country", "TimeZoneName", "Abbreviation", "Latitude", "Longitude", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
