server:
  port: 9600

logging:
  config: classpath:logback.xml

xxl:
  job:
    admin:
      addresses: "http://127.0.0.1:8080/xxl-job-admin"
    accessToken: default_token
    executor:
      appname: xxl-job-executor-sample
      address: ""
      ip: ""
      port: 8888
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
